package App::Yath2::Schema::Overlay::ApiKey;
our $VERSION = '2.000000';

package
    App::Yath2::Schema::Result::ApiKey;
use utf8;
use strict;
use warnings;

use Carp qw/confess/;
confess "You must first load a App::Yath2::Schema::NAME module"
    unless $App::Yath2::Schema::LOADED;

# TODO(DBIx::QuickORM): the binary-UUID flavors (Percona/MySQL/MariaDB) store
# api_keys.value as BINARY(16), but unlike Run.run_uuid / Session.session_uuid
# this column has no inflate/deflate hook, and the lookup paths
# (Controller/Upload, Controller/User, Overlay/User) search with the raw
# user-supplied string. So API-key create + auth are inconsistent on those
# flavors. A plain inflate_column is not enough (DBIC does not deflate
# where-clause values), so the search boundaries must also route through
# format_uuid_for_db. Defer the full fix to the QuickORM conversion.

1;

__END__

=pod

=encoding UTF-8

=head1 NAME

App::Yath2::Schema::Overlay::ApiKey - Overlay for ApiKey result class.

=head1 DESCRIPTION

This is where custom (not autogenerated) code for the ApiKey result class lives.

=head1 SOURCE

The source code repository for Test2-Harness can be found at
L<http://github.com/Test-More/Test2-Harness/>.

=head1 MAINTAINERS

=over 4

=item Chad Granum E<lt>exodist@cpan.orgE<gt>

=back

=head1 AUTHORS

=over 4

=item Chad Granum E<lt>exodist@cpan.orgE<gt>

=back

=head1 COPYRIGHT

Copyright Chad Granum E<lt>exodist7@gmail.comE<gt>.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

See L<http://dev.perl.org/licenses/>

=cut

=pod

=cut POD NEEDS AUDIT

