package Test2::Harness2::Role::Resource::Utilizer;
use strict;
use warnings;

our $VERSION = '2.000013';

use Carp qw/croak/;

# Role::Tiny must mark this as a role before HashBase loads.
use Role::Tiny;
use Object::HashBase qw{
    &Test2::Harness2::Role::Resource
    <utilize_percent
    <min_concurrent
};

requires 'is_temporarily_unavailable';

sub set_utilize_percent {
    my ($self, $pct) = @_;
    $self->{+UTILIZE_PERCENT} = $self->_validate_utilize_percent($pct);
    return;
}

# Scheduler-level check. Reads the scheduler's shared in-flight count
# via the base role's in_flight() accessor. Defer only when saturated
# AND in-flight already meets the min_concurrent floor (default 1) --
# below the floor, at least min_concurrent tests are always allowed
# to run even if the subsystem never drops back below threshold.
sub should_defer_for_utilization {
    my $self = shift;
    my $min  = $self->{+MIN_CONCURRENT} // 1;
    return 0 if $self->in_flight < $min;
    return $self->is_temporarily_unavailable ? 1 : 0;
}

# Validate 0 < pct < 100. Returns the validated value.
sub _validate_utilize_percent {
    my ($self, $pct) = @_;

    croak ref($self) . "::set_utilize_percent requires a numeric percentage"
        unless defined $pct && $pct =~ m/^[0-9]+(?:\.[0-9]+)?\z/;

    croak ref($self) . "::set_utilize_percent percentage must be > 0 and < 100 (got '$pct')"
        unless $pct > 0 && $pct < 100;

    return $pct;
}

1;

__END__

=pod

=encoding UTF-8

=head1 NAME

Test2::Harness2::Role::Resource::Utilizer - Utilization-aware resource role.

=head1 DESCRIPTION

This role layers utilization-aware behaviour on top of
L<Test2::Harness2::Role::Resource>. A consumer of both roles:

=over 4

=item *

Implements the base resource contract (C<available>, C<assign>,
C<release>, C<status>).

=item *

Accepts a percentage threshold (C<0 E<lt> pct E<lt> 100>) describing
how heavily loaded its monitored subsystem -- CPU load, free memory,
free C</tmp> space, etc. -- is allowed to be before the resource
starts deferring new assignments.

=item *

Implements C<is_temporarily_unavailable> as a predicate that reports
whether the monitored subsystem is currently saturated. The scheduler
calls L</should_defer_for_utilization> (provided by this role) which
adds a starvation guard: while in-flight assignments stay below
C<min_concurrent> (default C<1>) saturation does not defer, so at
least C<min_concurrent> tests can always be running even if the
subsystem never drops back below the threshold.

=back

The role does B<not> alter the base contract. Resources that consume
both roles still go through the same scheduler walk:

    needed -> is_permanent_broken -> is_usable
           -> should_defer_for_utilization
           -> available -> assign

C<should_defer_for_utilization> folds in between C<is_usable> and
C<available>.

=head1 REQUIRED METHODS

=over 4

=item $bool = $resource->is_temporarily_unavailable

Return true when the resource's monitored subsystem is currently
above the configured threshold, false otherwise. The scheduler does
not call this directly; it calls L</should_defer_for_utilization>
which delegates here after applying the starvation guard.

=back

=head1 PROVIDED METHODS

=over 4

=item $bool = $resource->should_defer_for_utilization

Scheduler hook. Reads the current in-flight count via the base role's
C<in_flight> accessor, which derefs the scheduler's shared scalar
ref. Returns true only when both:

=over 4

=item *

C<in_flight> is at least C<min_concurrent>; and

=item *

C<is_temporarily_unavailable> returns true.

=back

Below the C<min_concurrent> floor the saturation check is skipped so
the scheduler never starves -- at least C<min_concurrent> tests are
always permitted to run even when the subsystem stays pinned above
the utilization threshold.

=item $n = $resource->min_concurrent

Read-only accessor for the starvation-floor count, generated by
L<Object::HashBase> from the role's C<< <min_concurrent >> slot.
Defaults to C<1>; set at construction time via
C<< MyResource->new(min_concurrent => N) >>.

=item $pct = $resource->utilize_percent

Read-only accessor for the configured threshold. Generated by
L<Object::HashBase> from the role's C<< <utilize_percent >> slot;
consumers that import the role via the C<&> prefix inherit both the
accessor and the C<UTILIZE_PERCENT> constant.

=item $resource->set_utilize_percent($pct)

Validate (via C<_validate_utilize_percent> below) and store the
threshold into the C<utilize_percent> slot. Receives the percentage
from C<--utilize> / C<-U>. The role's default implementation is
suitable for any resource that wants the value stored and nothing
else; resources that need to react to changes (re-prime a sampler,
flush a cached threshold, etc.) override.

=item $pct = $resource->_validate_utilize_percent($pct)

Helper for use inside a custom C<set_utilize_percent> override.
Validates that C<$pct> is numeric and strictly between C<0> and
C<100>; croaks otherwise. Returns the validated value so the caller
can store it directly.

=back

=head1 SPAWN-THROTTLE PAIRING

The percentage gate alone is not sufficient: a freshly spawned test
needs a moment to actually consume CPU/memory/disk before the
resource sample reflects it. L<Test2::Harness2::Resource::Throttle>
complements the utilizer gate by capping how many tests can be in
their just-spawned phase at once, measured over a sliding window.
See that module for the rule grammar and adaptive scaling.

=head1 SEE ALSO

L<Test2::Harness2::Role::Resource> -- the base resource contract.

L<App::Yath2::Options::Resource> -- the C<--utilize> / C<-U> option
that supplies the percentage threshold.

=head1 SOURCE

L<https://github.com/Test-More/Test2-Harness>

=head1 AUTHORS

=over 4

=item Chad Granum E<lt>exodist@cpan.orgE<gt>

=back

=head1 COPYRIGHT

Copyright Chad Granum E<lt>exodist7@gmail.comE<gt>.

See L<https://dev.perl.org/licenses/>

=cut
